name: publish
on: [push]
jobs:
  publish-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the image
        run: |
          docker build . --file $GITHUB_WORKSPACE/Containerfile --tag ghcr.io/cidrblock/dev-spaces-container:latest
          docker push ghcr.io/cidrblock/dev-spaces-container:latest